---[SHARED] Registers a function to be called on each of an entity's bones when duplicator.ApplyBoneModifiers is called.
---
--- This function is available to call on the client, but registered functions aren't used anywhere!
---
---[(View on wiki)](https://wiki.facepunch.com/gmod/duplicator.RegisterBoneModifier)
---@param key any The type of the key doesn't appear to matter, but it is preferable to use a string.
---@param boneModifier fun(ply: Player, ent: Entity, boneID: number, bone: PhysObj, data: table) Function called on each bone that an ent has. Called during duplicator.ApplyBoneModifiers.
--- Function parameters are:
--- * Player ply
--- * Entity ent
--- * number boneID
--- * PhysObj bone
--- * table data
---
---
--- The data table that is passed to boneModifier is set with duplicator.StoreBoneModifier
function duplicator.RegisterBoneModifier(key, boneModifier) end
