---[CLIENT] Allows you to play external sound files, as well as online radio streams.
--- You can find a list of all error codes [here](http://www.un4seen.com/doc/#bass/BASS_ErrorGetCode.html)
---
--- For offline file playback, see sound.PlayFile.
---
--- Due to a bug with [BASS](http://www.un4seen.com/), AAC codec streams cannot be played in 3D mode.
---
---[(View on wiki)](https://wiki.facepunch.com/gmod/sound.PlayURL)
---@param url string The URL of the sound to play
---@param flags string Flags for the sound. Can be one or more of following, separated by a space (`" "`):
--- * 3d - Makes the sound 3D, so you can set its position
--- * mono - Forces the sound to have only one channel
--- * noplay - Forces the sound not to play as soon as this function is called
--- * noblock - Disables streaming in blocks. It is more resource-intensive, but it is required for IGModAudioChannel:SetTime.
---
---
---
---
--- If you don't want to use any of the above, you can just leave it as `""`.
---@param callback fun(soundchannel: IGModAudioChannel, errorID: number, errorName: string) Callback function that is called as soon as the the stream is loaded. It has the following arguments:
--- * IGModAudioChannel soundchannel - The sound channel
--- * number errorID - ID of an error, if an error has occured
--- * string errorName - Name of an error, if an error has occured
function sound.PlayURL(url, flags, callback) end
