---[CLIENT AND MENU] Downloads a file from the supplied addon and saves it as a .cache file in garrysmod/cache folder.
---
--- This is mostly used to download the preview image of the addon, but the game seems to also use it to download replays and saves.
---
--- In case the retrieved file is an image and you need the IMaterial, use Global.AddonMaterial with the path supplied from the callback.
---
---[(View on wiki)](https://wiki.facepunch.com/gmod/steamworks.Download)
---@param workshopPreviewID string The Preview ID of workshop item.
---@param uncompress boolean Whether to uncompress the file or not, assuming it was compressed with LZMA.
--- You will usually want to set this to true.
---@param resultCallback fun(pathToSavedFile: string) The function to process retrieved data. The first and only argument is a string, containing path to the saved file.
function steamworks.Download(workshopPreviewID, uncompress, resultCallback) end
